runtime: java11
instance_class: F2
entrypoint: 'java -jar /workspace/build/libs/assignment01-0.0.1-SNAPSHOT.jar'
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  max_instances: 1
